export const SITE_CONTENT = {
  name: "Rajat Chaturvedi",
  email: "chaturvedirajat36@gmail.com",
  whatsappNumber: "918979966510",
  title: "Rajat Chaturvedi | FullStack Developer",
  description: "A master was once a beginner ...",
};

export const UI_CONTENT = {
  lists: {
    showMore: "Show more",
    showLess: "Show less",
    experienceCount: 3,
    credentialCount: 5,
    writingCount: 3,
    caseStudyCount: 3,
    testimonialCount: 3,
    awardCount: 5,
    projectCount: 6,
    projectRows: 2,
  },
  maintenance: {
    label: `${SITE_CONTENT.name} / Portfolio`,
    title: "Site under maintenance",
    message: "My portfolio is temporarily unavailable. Please check back soon, or get in touch directly.",
    contactLabel: "Get in touch",
  },
  about: {
    typewriterFallback: `Hi, I am ${SITE_CONTENT.name}.`,
    loading: "Loading...",
    learnMore: "View Resume",
    contactMe: "Contact Me",
    contactHref: "#contact",
  },
  headings: {
    awards: "Awards",
    caseStudies: "Featured Case Studies",
    experience: "Experience",
    process: "How I Build",
    projects: "Projects",
    skills: "Skills",
    testimonials: "Testimonials",
    writing: "Writing and Notes",
  },
  caseStudies: {
    problem: "Problem:",
    solution: "Solution:",
    outcome: "Outcome:",
    live: "Live",
    source: "Source",
  },
  experience: { companyJoiner: "at" },
  contact: {
    title: "Contact",
    prompt: "Connect for any query",
    response: "To get revert from Rajat",
    name: "Name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    submit: "Submit",
  },
  cta: {
    email: "Email Me",
    resume: "View Resume",
    calendar: "Book a Call",
    slots: "View all slots",
  },
  header: {
    initials: "RC",
    firstName: "Rajat",
    lastName: "Chaturvedi",
    linkedin: "LinkedIn",
    github: "GitHub",
    resume: "Resume",
    openMenu: "Open navigation menu",
    closeMenu: "Close navigation menu",
    navigation: "Mobile navigation",
    fallbackLinks: {
      github: "https://github.com/Rajat-Chaturvedi",
      linkedin: "https://www.linkedin.com/in/rajat-chaturvedi-dev",
      resume: "https://drive.google.com/file/d/1e6DBbFVqU1U2_ZAqaSxWmLPoHe4Y9sXQ/view?usp=sharing",
    },
    maintenanceNav: [{ href: `mailto:${SITE_CONTENT.email}`, label: "Contact" }],
    nav: [
      { href: "#about", label: "About" },
      { href: "#experience", label: "Works" },
      { href: "#skills", label: "Skills" },
      { href: "#case-studies", label: "Case Studies" },
      { href: "#projects", label: "Projects" },
      { href: "#certifications", label: "Credentials" },
      { href: "#testimonials", label: "Testimonials" },
      { href: "#now", label: "Now" },
      { href: "#writing", label: "Writing" },
      { href: "#awards", label: "Awards" },
      { href: "#contact", label: "Contact" },
    ],
  },
  now: {
    focus: "Current Focus",
    learning: "Learning",
    building: "Building",
    availability: "Availability",
  },
  project: {
    stack: "Technologies",
    openLink: "Open project in a new tab",
    details: "View project",
    back: "All projects",
    overview: "Overview",
    visit: "Visit live site",
    role: "My role",
    problem: "Challenge",
    solution: "Approach",
    outcome: "Outcome",
    next: "Next project",
  },
  credentials: {
    title: "Certifications & Education",
    viewAll: "View credentials",
    back: "Back to portfolio",
    education: "Education",
    workshop: "Certified workshop",
    certification: "Course certificate",
    openExternal: "Open certificate in a new tab",
    viewImage: "View certificate image",
    all: "All credentials",
    imageAlt: "Certificate for",
  },
  writing: {
    readArticle: "Read article",
    viewAll: "All articles",
    back: "Back to portfolio",
    external: "Opens in a new tab",
    empty: "No published articles yet.",
  },
  whatsapp: {
    message: "Hello! I want to connect regarding fulltime opportunity / freelance.",
    label: "Chat on WhatsApp",
  },
};