export const SITE_CONTENT = {
  name: "Rajat Chaturvedi",
  email: "chaturvedirajat36@gmail.com",
  whatsappNumber: "918979966510",
  title: "Rajat Chaturvedi | FullStack Developer",
  description: "A master was once a beginner ...",
};

export const UI_CONTENT = {
  maintenance: {
    label: `${SITE_CONTENT.name} / Portfolio`,
    title: "Site under maintenance",
    message: "My portfolio is temporarily unavailable. Please check back soon, or get in touch directly.",
    contactLabel: "Get in touch",
  },
  about: {
    typewriterFallback: `Hi, I am ${SITE_CONTENT.name}.`,
    loading: "Loading...",
    learnMore: "Learn More",
    contactMe: "Contact Me",
    contactHref: "#contact",
  },
  headings: {
    awards: "Awards",
    caseStudies: "Featured Case Studies",
    experience: "Experience",
    process: "How I Build",
    projects: "Projects",
    skills: "Skills",
    testimonials: "Testimonials",
    writing: "Writing and Notes",
  },
  caseStudies: {
    problem: "Problem:",
    solution: "Solution:",
    outcome: "Outcome:",
    live: "Live",
    source: "Source",
  },
  experience: { companyJoiner: "at" },
  contact: {
    title: "Contact",
    prompt: "Connect for any query",
    response: "To get revert from Rajat",
    name: "Name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    submit: "Submit",
  },
  cta: {
    email: "Email Me",
    resume: "View Resume",
    calendar: "Book a Call",
    slots: "View all slots",
  },
  header: {
    initials: "RC",
    firstName: "Rajat",
    lastName: "Chaturvedi",
    linkedin: "LinkedIn",
    github: "GitHub",
    resume: "Resume",
    fallbackLinks: {
      github: "https://github.com/Rajat-Chaturvedi",
      linkedin: "https://www.linkedin.com/in/rajat-chaturvedi-dev",
      resume: "https://drive.google.com/file/d/144BvkzYWkgwLh_f0H06EHbIoIq-2wBzl/view?usp=sharing",
    },
    maintenanceNav: [{ href: `mailto:${SITE_CONTENT.email}`, label: "Contact" }],
    nav: [
      { href: "#about", label: "About" },
      { href: "#experience", label: "Works" },
      { href: "#skills", label: "Skills" },
      { href: "#case-studies", label: "Case Studies" },
      { href: "#projects", label: "Projects" },
      { href: "#testimonials", label: "Testimonials" },
      { href: "#now", label: "Now" },
      { href: "#writing", label: "Writing" },
      { href: "#awards", label: "Awards" },
      { href: "#contact", label: "Contact" },
    ],
  },
  now: {
    focus: "Current Focus",
    learning: "Learning",
    building: "Building",
    availability: "Availability",
  },
  project: { stack: "Stack :" },
  writing: { readArticle: "Read article" },
  whatsapp: {
    message: "Hello! I want to connect regarding fulltime opportunity / freelance.",
    label: "Chat on WhatsApp",
  },
};